### PR TITLE
Use navbar html that's local

### LINKED ISSUE #2: Use navbar html that's local
We should probably use the navbar html that's in the action repository:

```yaml
  navbar-url:
    description: 'URL of the navbar HTML to be inserted.'
    required: false
    default: ${{ github.action_path }}/scripts/TuringNavbar.html
```

The insert_navbar.sh script will have to be modified for this though because it uses `curl` right now (whereas if it's local we probably just want to use `cat`).

### PR DESCRIPTION
**Pull request by shravanngoswamii**
closes #2

### CODE REVIEW

**Comment by shravanngoswamii** [comment]
For Turing, should we keep navbar HTML in this repo or in our main site repo? I guess navbar is eventually handled here so we can keep it here!

**Comment by penelopeysm** [comment]
This is great :) I would keep the html together with the action in the same repo, but also I wonder if it's time to move this repo to TuringLang too? (I can do that since I have admin rights)

**Review by penelopeysm — APPROVED** [review]

**Comment by penelopeysm** [comment]
Hmm - I'm wrong - one shouldn't need admin rights to make a new organisation repo, and actually probably you're the only one who can move this repo since it's yours :P

**Comment by shravanngoswamii** [comment]
> I would keep the html together with the action in the same repo, but also I wonder if it's time to move this repo to TuringLang too?

I think it's working fine and ready to move! Should we ask someone before moving? Because `TuringLang` only have repo's that are related to Turing ecosystem, I think this one is more suitable for [`JuliaDocs`](https://github.com/JuliaDocs) organization if we can generalize this for all...!

**Comment by shravanngoswamii** [comment]
> Hmm - I'm wrong - one shouldn't need admin rights to make a new organisation repo, and actually probably you're the only one who can move this repo since it's yours :P

Ohh yes, I have transfer rights!

**Comment by penelopeysm** [comment]
We _could_ generalise it, but I'm not seeing the benefit of doing so right now. After all, the navbar html we have is very Turing-specific.

Do you know if there are there other people out there who could make use of this action too?

**Comment by shravanngoswamii** [comment]
> Do you know if there are there other people out there who could make use of this action too?

Yes, I am aware of [SciMl](https://docs.sciml.ai/Overview/stable/) and [Julia Quantum Control](https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/), SciML is using MultiDocumenter and Julia Quantum Control is using their own navbar manually using JavaScript!

**Comment by penelopeysm** [comment]
Hmmm... My opinion is that the approaches between all three are sufficiently disparate that it would be additional effort for them to adapt to using this workflow. Definitely at least for MultiDocumenter – our script can't replace that. The JS script in JuliaQuantumControl is doing basically the same thing as us in that it's injecting HTML into the start of the body tag, but their HTML is dynamically generated and differs for each repo (e.g. https://github.com/JuliaQuantumControl/QuantumControl.jl/blob/bf7a15e9c9d042ead4e7afa439a875dec631092c/docs/src/assets/topbar/topbar.js#L45-L47) whereas here we use a fixed HTML content.

**Comment by shravanngoswamii** [comment]
Let's keep our current setup as it is and not interfere in it much! `Documenter.jl` also have the issue related to native top navbar - https://github.com/JuliaDocs/Documenter.jl/issues/2177, so maybe that will be solved someday!

**Comment by penelopeysm** [comment]
Okay:)

**Comment by shravanngoswamii** [comment]
Let's merge this PR, let me know when to transfer this repo to `TuringLang`!

**Comment by shravanngoswamii** [comment]
Thank You @penelopeysm!!

**Comment by penelopeysm** [comment]
Feel free to go ahead with the transfer :)

thank _you_ @shravanngoswamii!

**Comment by shravanngoswamii** [comment]
> Feel free to go ahead with the transfer :)

Done! Do you have rights to make me admin in this repo?

**Comment by penelopeysm** [comment]
Done!

**Comment by shravanngoswamii** [comment]
> Done!

Thank You! I think we should create a release so no-one uses the wrong release, just in case!

**Comment by penelopeysm** [comment]
Yup, agreed

**Pull request merged**
